Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: app.handler
      CodeUri: C:\Users\ss\PycharmProjects\pythonProject\backup_everything\src
      Runtime: python3.9
      Architectures:
        - x86_64