version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "be3cloud-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1nmrsoyttk3ot"
s3_prefix = "be3cloud-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Client=\"https://example.com\" TestWithPostman=\"true\""
