## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
## SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cognito to API Gateway HTTP API (JWT)

Parameters:
  Client:
    Description: Client website for authentication redirects and cors (must start with https://)
    Type: String
    Default: https://example.com
  TestWithPostman:
    Description: Do you need to test with Postman? (Not recommended for production)
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"

Globals:
  Function:
    Timeout: 300
    Runtime: python3.9
    Tracing: Active
    Architectures:
      - arm64

Resources:
  # Creates a nested stack with the required Cognito requirements
  AuthStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./auth.yaml
      Parameters:
        ClientDomain: !Ref Client
        Postman: !Ref TestWithPostman

  # Creates an API Gateway HTTP API endpoint with JWT authorization
  AuthApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Description: Cognito to HTTP API demo
      CorsConfiguration:
        AllowMethods:
          - GET
        AllowOrigins:
          - !Ref Client
      Auth:
        Authorizers:
          OAuth2Authorizer:
            AuthorizationScopes:
              - email
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              issuer: !GetAtt AuthStack.Outputs.Issuer
              audience:
                - !GetAtt AuthStack.Outputs.UserPoolClientId
        DefaultAuthorizer: OAuth2Authorizer

  # create a baseapi to without auth
  BaseApi:
      Type: AWS::Serverless::HttpApi
      Properties:
        Description: Base HTTP API for without auth
        CorsConfiguration:
            AllowMethods: ["*"]
            AllowOrigins: ["*"]

  # Creates a Lambda function to handle the API Gateway HTTP API request
  CognitoFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-CognitoFunction
      CodeUri: src/
      Handler: app.handler
#      Layers:
#        - !Ref CognitoLayer
      Events:
        # base api for without auth
        Be3AppAPI:
          Type: HttpApi
          Properties:
            ApiId: !Ref BaseApi
            Path: /
            Method: ANY
#        # api for auth
#        CognitoAPI:
#          Type: HttpApi
#          Properties:
#            ApiId: !Ref AuthApi
#            Path: /auth
#            Method: ANY

#  CognitoLayer:
#    Type: AWS::Serverless::LayerVersion
#    Properties:
#      LayerName: !Sub ${AWS::StackName}-Cognito-Layer
#      Description: Package Layer for Be3 API Cognito
#      ContentUri: ./libs/python.zip
#      CompatibleRuntimes:
#        - python3.9
#      LicenseInfo: 'MIT'
#      RetentionPolicy: Retain

Outputs:
  BaseApiEndpoint:
    Description: Base API endpoint
    Value: !Sub https://${BaseApi}.execute-api.${AWS::Region}.amazonaws.com
  AuthApiEndpoint:
    Description: Auth API endpoint
    Value: !Sub https://${AuthApi}.execute-api.${AWS::Region}.amazonaws.com/auth
  AuthUrl:
    Description: Cognito Auth URL
    Value: !GetAtt AuthStack.Outputs.AuthUrl
